### PR TITLE
Objects

### PR DESCRIPTION
**Pull request by MCJOHN974**
@yegor256 , here i add counting of left items in carts and fix bug in ```Digitals::deliver()```.

### CODE REVIEW

**Comment by yegor256** [comment]
@MCJOHN974 are you sure you want to delete all these files? Why?

**Comment by MCJOHN974** [comment]
@yegor256 i thought you will take ```objects.cpp``` from my fork and keep other files from yours

**Comment by MCJOHN974** [comment]
Now i return all other files except ```functions.c```

**Comment by yegor256** [comment]
@MCJOHN974 thanks!

**Pull request merged**
